# Generated by Django 5.2.13 on 2026-05-19 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='roles_needed',
            field=models.TextField(default='', help_text='Comma separated list of roles needed'),
        ),
    ]
